name: Auto Merge Release to Main

on:
  pull_request:
    types: [closed]
    branches:
      - release_*
          
jobs:
  create-and-merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Extract branch names
        id: extract-names
        run: |
          echo "::set-output name=release_branch::$(echo '${{ github.ref }}' | sed 's/refs\/heads\///')"
          echo "::set-output name=hr_branch::$(echo '${{ github.event.pull_request.head.ref }}')"

      - name: Check for changes from new branch to main
        id: check-diff
        run: |
          git fetch origin main
          if git diff --quiet origin/main..${{ steps.extract-names.outputs.release_branch }}; then
            echo "::set-output name=has_changes::false"
          else
            echo "::set-output name=has_changes::true"
          fi

      - name: Create new branch
        if: steps.check-diff.outputs.has_changes == 'true'
        id: create-branch
        run: |
          new_branch="${{ steps.extract-names.outputs.release_branch }}_to_develop"
          git fetch origin ${{ steps.extract-names.outputs.release_branch }}
          git checkout -B $new_branch origin/${{ steps.extract-names.outputs.release_branch }}
          git push --force origin $new_branch

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Pull Request
        id: create-pr
        run: |
          pr_url=$(gh pr create --title "Merge ${{ steps.extract-names.outputs.release_branch }} to main" --body "This is an automated pull request created by GitHub Actions." --base main --head ${{ steps.extract-names.outputs.release_branch }}_to_develop --assignee copy202 )
          pr_url=$(gh pr create --title "Merge test-001 to main" --body "This is an automated pull request created by GitHub Actions." --base main --head test-001 --assignee "copy202")
          echo "pr_url=${pr_url}" >> $GITHUB_ENV
