name: Auto Merge Release to Trunk

on:
  pull_request:
    types: [closed]
    branches:
      - release_*

env:
  TARGET_BRANCH: main
          
jobs:
  create-and-merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Extract branch names
        id: extract-names
        run: |
          echo "release_branch=$(echo '${{ github.ref }}' | sed 's/refs\/heads\///')" >> $GITHUB_OUTPUT
          echo "hr_branch=$(echo '${{ github.event.pull_request.head.ref }}')" >> $GITHUB_OUTPUT
          echo "new_branch=$(echo '${{ github.ref }}' | sed 's/refs\/heads\///')_to_${{ env.TARGET_BRANCH }}" >> $GITHUB_OUTPUT

      - name: Check for changes from new branch to ${{ env.TARGET_BRANCH }}
        id: check-diff
        run: |
          git fetch origin ${{ env.TARGET_BRANCH }}
          if git diff --quiet origin/${{ env.TARGET_BRANCH }}..${{ steps.extract-names.outputs.release_branch }}; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create new branch
        if: steps.check-diff.outputs.has_changes == 'true'
        id: create-branch
        run: |
          git fetch origin ${{ steps.extract-names.outputs.release_branch }}
          git checkout -B ${{ steps.extract-names.outputs.new_branch }} origin/${{ steps.extract-names.outputs.release_branch }}
          git push --force origin ${{ steps.extract-names.outputs.new_branch }}

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Pull Request
        id: create-pr
        run: |
          pr_url=$(gh pr create --title "Merge ${{ steps.extract-names.outputs.release_branch }} to ${{ env.TARGET_BRANCH }}" --body "This is an automated pull request created by GitHub Actions." --base ${{ env.TARGET_BRANCH }} --head ${{ steps.extract-names.outputs.new_branch }} --assignee copy202 )
          echo "pr_url=${pr_url}" >> $GITHUB_ENV
