name: Release to Develop

on:
  push:
    branches:
      - release_*

jobs:
  release_to_develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.email "fenggwyq@gmail.com"
          git config --global user.name "fenggwyq"

      - name: Create release_to_develop branch
        run: |
          git checkout -b $(echo ${GITHUB_REF} | cut -d'/' -f3)_to_develop
          git push -u origin $(echo ${GITHUB_REF} | cut -d'/' -f3)_to_develop

      - name: Merge release_to_develop to develop
        id: merge
        run: |
          git fetch
          git pull origin main
          git rebase main
          git checkout main
          git merge $(echo ${GITHUB_REF} | cut -d'/' -f3)_to_develop --allow-unrelated-histories
          git push origin main
        continue-on-error: false

      # - name: Send Slack notification
      #   if: always()
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   with:
      #     text: |
      #       ${{ github.event.repository.name }}: Release branch ${{ github.ref }} has been merged to develop branch.
      #     color: ${{ steps.merge.outcome == 'success' ? 'good' : 'danger' }}
      #     fields: |
      #       - Field 1: Value 1
      #       - Field 2: Value 2

      - name: Delete release_to_develop branch
        if: steps.merge.outcome == 'success'
        run: |
          git push -d origin $(echo ${GITHUB_REF} | cut -d'/' -f3)_to_develop
