name: test

on:
  workflow_dispatch:

jobs:
  create-and-merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"


      - name: Create Pull Request
        id: create-pr
        run: |
          pr_url=$(gh pr create --title "Merge test-001 to main" --body "This is an automated pull request created by GitHub Actions." --base main --head test-001 --assign copy202 --json url -q ".url")
          echo "pr_url=${pr_url}" >> $GITHUB_ENV

